"""
Pydantic contracts and schemas for document intelligence extraction
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class BoundingBox(BaseModel):
    page: int
    left: float
    top: float
    right: float
    bottom: float

class CitationItem(BaseModel):
    citation_id: int
    chunk_id: str
    document_id: str
    document_name: str
    page_number: Optional[int] = None
    section: Optional[str] = None
    text_excerpt: str
    relevance_score: Optional[float] = None
    bounding_boxes: Optional[List[BoundingBox]] = None

class ContractExtraction(BaseModel):
    parties: Optional[List[str]] = Field(default=None, description="Names of contracting parties or entities")
    effective_date: Optional[str] = Field(default=None, description="Contract effective or execution date")
    payment_terms: Optional[str] = Field(default=None, description="Payment schedule, net terms, penalties")
    renewal: Optional[str] = Field(default=None, description="Automatic renewal, notice window, or duration")
    termination_provisions: Optional[str] = Field(default=None, description="Termination for convenience or cause")
    governing_law: Optional[str] = Field(default=None, description="Jurisdiction or governing law")
    contract_value: Optional[str] = Field(default=None, description="Total contract amount or rate")
    key_obligations: Optional[List[str]] = Field(default=None, description="Core deliverables or promises")
    legal_disclaimer: str = Field(
        default="This extraction is generated by DocuMind for informational purposes and does not constitute legal advice."
    )
    citations: List[CitationItem] = Field(default_factory=list)

class InvoiceLineItem(BaseModel):
    description: str
    quantity: Optional[float] = None
    unit_price: Optional[float] = None
    amount: float

class InvoiceExtraction(BaseModel):
    supplier_name: Optional[str] = Field(default=None, description="Vendor or supplier company name")
    customer_name: Optional[str] = Field(default=None, description="Billed customer or client name")
    invoice_number: Optional[str] = Field(default=None, description="Invoice reference code or number")
    invoice_date: Optional[str] = Field(default=None, description="Date of issuance")
    due_date: Optional[str] = Field(default=None, description="Payment due date")
    currency: Optional[str] = Field(default=None, description="Currency code, e.g. USD, EUR")
    subtotal: Optional[float] = Field(default=None, description="Pre-tax amount")
    tax_amount: Optional[float] = Field(default=None, description="Tax or VAT amount")
    total_amount: Optional[float] = Field(default=None, description="Grand total payable")
    line_items: List[InvoiceLineItem] = Field(default_factory=list)
    citations: List[CitationItem] = Field(default_factory=list)

class DocumentSummary(BaseModel):
    document_title: str
    executive_overview: str
    key_findings: List[str]
    identified_risks_or_obligations: List[str]
    citations: List[CitationItem] = Field(default_factory=list)

class DocumentComparisonItem(BaseModel):
    topic: str
    doc_a_position: str
    doc_b_position: str
    status: str = Field(description="'aligned', 'divergent', or 'exclusive'")

class DocumentComparison(BaseModel):
    document_a_id: str
    document_a_name: str
    document_b_id: str
    document_b_name: str
    summary_of_comparison: str
    topics: List[DocumentComparisonItem]
    citations: List[CitationItem] = Field(default_factory=list)
